FROM python:3.9.4

RUN pip3 install \
    flask \
    SQLAlchemy \
    Flask-SQLAlchemy \
    PyMySQL \
    Flask-Migrate \
    flask-marshmallow \
    marshmallow-sqlalchemy \
    pytest \
    python-dotenv

WORKDIR /works