version: '3'
services:
    python:
        build: './docker/python'
        tty: true
        ports:
            - '5000:5000'
        volumes:
            - '.:/works'
    mysql:
        image: 'mysql:5.7'
        ports:
            - '3306:3306'
        volumes:
            - 'mysql-data:/var/lib/mysql'
        environment: 
            MYSQL_ROOT_PASSWORD: 'default'
            MYSQL_USER: 'default'
            MYSQL_PASSWORD: 'default'
volumes:
    mysql-data: